name: dart_gbk
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/dozenlue/DartGBK
author: Dozen Lue

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
